/* Licensed at AlphaOri Technologies */
package com.cpdss.dischargeplan.service.utility;

public enum ProcessIdentifiers {
  discharging_information,
  discharging_information_status,
  discharging_stages_min_amount,
  discharging_stages_duration,
  cow_plan_details,
  cow_with_different_cargo,
  cow_tank_details,
  discharging_delay,
  discharging_delay_reason,
  discharging_machinary_in_use,
  discharging_port_tide_details,
  discharging_berth_details,
  discharging_information_algo_status,
  algo_error_heading,
  algo_errors,
  discharging_sequence,
  ballast_valves,
  cargo_valves,
  cargo_discharging_rate,
  ballast_operation,
  discharging_plan_portwise_details,
  ballasting_rate,
  deballasting_rate,
  discharging_plan_stowage_details,
  discharging_plan_ballast_details,
  discharging_plan_rob_details,
  discharging_plan_stability_parameters,
  discharging_plan_commingle_details,
  discharging_sequence_stability_parameters,
  port_discharging_plan_stowage_ballast_details,
  port_discharging_plan_rob_details,
  port_discharging_plan_stability_parameters,
  port_discharging_plan_stowage_details,
  port_discharge_plan_commingle_details,
  json_data,
  loadable_pattern;
}
