/* Licensed at AlphaOri Technologies */
package com.cpdss.loadablestudy.utility;

public enum ProcessIdentifiers {
  voyage,
  loadable_study,
  comingle_cargo,
  cargo_nomination,
  loadable_study_port_rotation,
  on_hand_quantity,
  on_board_quantity,
  loadable_quantity,
  synoptical_table,
  json_data,
  loadable_study_algo_status,
  loadable_pattern,
  algo_error_heading,
  algo_errors,
  loadable_plan_constraints,
  loadable_plan_quantity,
  loadable_plan_commingle_details,
  loadable_pattern_cargo_topping_off_sequence,
  loadable_plan_stowage_details,
  loadable_plan_ballast_details,
  loadable_plan_commingle_details_portwise,
  stability_parameters,
  loadable_pattern_cargo_details,
  loadable_plan,
  loadable_plan_stowage_ballast_details,
  loadicator_data_for_synoptical_table,
  cargo_nomination_operation_details,
  communication_status_update,
  port_instructions,
  cow_history,
  discharge_quantity_cargo_details,
  loadable_study_rules,
  loadable_study_rule_input,
  rule_vessel_mapping,
  rule_vessel_mapping_input,
  loadable_plan_comments,
  loadable_plan_stowage_details_temp,
  loadable_pattern_algo_status,
  discharge_cow_details,
  loadable_study_attachments,
  pyuser,
  port_wise_time_required_for_loading
}
