/* Licensed at AlphaOri Technologies */
package com.cpdss.loadingplan.utility;

public enum ProcessIdentifiers {
  port_loading_plan_stability_parameters,
  port_loading_plan_rob_details,
  loading_plan_ballast_details,
  loading_plan_rob_details,
  loading_plan_portwise_details,
  port_loading_plan_stowage_ballast_details,
  port_loading_plan_stowage_ballast_details_temp,
  port_loading_plan_stowage_details,
  port_loading_plan_stowage_details_temp,
  loading_sequence,
  loading_plan_stowage_details,
  loading_sequence_stability_parameters,
  loading_plan_stability_parameters,
  loading_information,
  cargo_topping_off_sequence,
  loading_berth_details,
  loading_delay,
  loading_delay_reason,
  loading_machinary_in_use,
  stages_min_amount,
  stages_duration,
  loading_information_status,
  loading_information_arrival_status,
  loading_information_departure_status,
  port_loadable_plan_commingle_details_temp,
  port_loadable_plan_commingle_details,
  bill_of_ladding,
  pyuser,
  voyage,
  loadable_pattern,
  loadicator_data_for_synoptical_table,
  ballast_operation,
  eduction_operation,
  cargo_loading_rate,
  json_data,
  loading_port_tide_details,
  algo_error_heading,
  algo_errors,
  loading_instructions,
  synoptical_table,
  loadable_study_port_rotation,
  loading_information_algo_status;
}
