/* Licensed at AlphaOri Technologies */
package com.cpdss.loadablestudy.domain;

public enum TableCellStyle {
  STOWAGE_PLAN_TITLE,
  FPT_CELL_STYLE,

  VESSEL_TANK_DESCRIPTION,
  VESSEL_TANK_TANK_NO,
  VESSEL_TANK_CARGO_CODE,
  VESSEL_TANK_ULLAGE,
  VESSEL_TANK_LOADED_PERCENTAGE,
  VESSEL_TANK_SHIPS_NBBLS,
  VESSEL_TANK_SHIPS_MT,
  VESSEL_TANK_SHIPS_KL_15C,
  VESSEL_TANK_DETAILS,

  CARGO_TITLES,
  CARGO_CARGO_CODE,
  CARGO_LOADING_PORT,
  CARGO_API,
  CARGO_TEMP,
  CARGO_CARGO_NOMINATION,
  CARGO_TOLERANCE,
  CARGO_NBBLS,
  CARGO_MT,
  CARGO_KL15C,
  CARGO_LT,
  CARGO_DIFF_BBLS,
  CARGO_DIFF_DIFF_PERCENTAGE,
  CARGO_TOTAL,
  CLOSED_CELL_STYLE,

  PORT_OPERATIONS_TITLES,
  PORT_OPERATIONS_VALUES;
}
