import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { CommonApiService } from '../../../shared/services/common/common-api.service';
import { IUllageUpdateDetails, IUllageSaveDetails, IUllageQuantityRequest, IUllageQuantityResponse, IUllageExcelResponse } from './../models/loading-discharging.model';
import { IResponse } from '../../../shared/models/common.model';

/**
 * Api Service for ullage update popup
 *
 * @export
 * @class UllageUpdateApiService
 */
@Injectable()
export class UllageUpdateApiService {

  constructor(
    private commonApiService: CommonApiService
  ) { }

  /**
   * Method for getting ullage details
   *
   * @param {number} vesselId
   * @param {number} patternId
   * @param {number} portRotationId
   * @param {string} status
   * @memberof UllageUpdateApiService
   */
  getUllageDetails(vesselId: number, patternId: number, portRotationId: number, status: string) {
    return this.commonApiService.get<IUllageUpdateDetails>(`vessels/${vesselId}/pattern/${patternId}/port/${portRotationId}/update-ullage/${status}`);
  }

  /**
   * Method for getting ullage quantity
   * @param {IUllageQuantityRequest}
   * @returns {IUllageQuantityResponse}
   * @memberof UllageUpdateApiService
   */
  getUllageQuantity(data, patternId) {
    return this.commonApiService.post<IUllageQuantityRequest, IUllageQuantityResponse>(`vessels/getUllageDetailsAlgo/${patternId}`, data);
  }

  /**
   * Method for save ullage data
   * @param {IUllageSaveDetails}
   * @returns {IResponse}
   * @memberof UllageUpdateApiService
   */
  updateUllage(data: IUllageSaveDetails) {
    return this.commonApiService.post<IUllageSaveDetails, IResponse>(`loading/ullage-bill-update`, data);
  }

  /**
   * Method for file upload
   * @param data
   * @memberof UllageUpdateApiService
   */
  uploadFile(data: FormData) {
    return this.commonApiService.postFormData<IUllageExcelResponse>(`import/ullage-report-file`, data);
  }

  /**
   * method for getting discharge-plan ullage details
   *
   * @param {number} vesselId
   * @param {number} patternId
   * @param {number} portRotationId
   * @param {string} status
   * @return {*}
   * @memberof UllageUpdateApiService
   */
  getDischargePlanUllageDetails(vesselId: number, patternId: number, portRotationId: number, status: string) {
    // TODO: uncomment code below when actual API data available.
    // return this.commonApiService.get<IUllageUpdateDetails>(`vessels/${vesselId}/pattern/${patternId}/port/${portRotationId}/discharging/ullage/${status}`);

    // this mock json will remove once actual API available
    const response = {
      "responseStatus": {
        "status": "200"
      },
      "billOfLaddingList": [
        {
          "cargoId": 33,
          "cargoColor": "#f3eb12",
          "cargoName": "Arabian Medium",
          "cargoAbbrevation": "ARM",
          "cargoNominationId": 17759,
          "cargoToBeDischarged": true,
          "cargoDischarged": false,
          "billOfLaddings": [
            {
              "id": 100000461,
              "portId": 2355,
              "cargoNominationId": 17759,
              "quantityBbls": 0.0000,
              "quantityMt": 0.0000,
              "quantityKl": 0.0000,
              "quantityLT": 0.0000,
              "api": 0.0000,
              "temperature": 0.0000,
              "blRefNo": ""
            }
          ]
        },
        {
          "cargoId": 32,
          "cargoColor": "#f21818",
          "cargoName": "Arabian Light",
          "cargoAbbrevation": "ARL",
          "cargoNominationId": 17760,
          "cargoToBeDischarged": true,
          "cargoDischarged": false,
          "billOfLaddings": [
            {
              "id": 100000462,
              "portId": 2355,
              "cargoNominationId": 17760,
              "quantityBbls": 0.0000,
              "quantityMt": 0.0000,
              "quantityKl": 0.0000,
              "quantityLT": 0.0000,
              "api": 0.0000,
              "temperature": 0.0000,
              "blRefNo": ""
            }
          ]
        }
      ],
      "cargoQuantityDetails": [
        {
          "cargoId": 33,
          "cargoColor": "#f3eb12",
          "cargoName": "Arabian Medium",
          "cargoAbbrevation": "ARM",
          "cargoNominationId": 17759,
          "nominationTotal": 188539.0,
          "maxTolerance": 10.0,
          "minTolerance": -10.0,
          "maxQuantity": 207392.9,
          "minQuantity": 169685.1,
          "plannedQuantityTotal": 0.0,
          "actualQuantityTotal": 0.0,
          "blQuantityMTTotal": 0.0,
          "blQuantityBblsTotal": 0.0,
          "blQuantityKLTotal": 0.0,
          "blQuantityLTTotal": 0.0,
          "difference": 0.0,
          "nominationApi": 30.8000,
          "nominationTemp": 105.4000,
          "actualAvgApi": 0.0,
          "actualAvgTemp": 0.0,
          "blAvgApi": 0.0,
          "blAvgTemp": 0.0
        },
        {
          "cargoId": 32,
          "cargoColor": "#f21818",
          "cargoName": "Arabian Light",
          "cargoAbbrevation": "ARL",
          "cargoNominationId": 17760,
          "nominationTotal": 78780.0,
          "maxTolerance": 10.0,
          "minTolerance": -10.0,
          "maxQuantity": 86658.0,
          "minQuantity": 70902.0,
          "plannedQuantityTotal": 0.0,
          "actualQuantityTotal": 0.0,
          "blQuantityMTTotal": 0.0,
          "blQuantityBblsTotal": 0.0,
          "blQuantityKLTotal": 0.0,
          "blQuantityLTTotal": 0.0,
          "difference": 0.0,
          "nominationApi": 33.4000,
          "nominationTemp": 118.8000,
          "actualAvgApi": 0.0,
          "actualAvgTemp": 0.0,
          "blAvgApi": 0.0,
          "blAvgTemp": 0.0
        }
      ],
      "isPlannedValues": true,
      "portDischargePlanBallastDetails": [
        {
          "cargoId": 0,
          "colorCode": "#01717D",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004187,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25597,
          "tankName": "FORE PEAK TANK",
          "tankShortName": "LFPT",
          "temperature": null,
          "quantity": 4800.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 13.1460,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "#01717D",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004188,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25598,
          "tankName": "NO.1 WATER BALLAST TANK",
          "tankShortName": "WB1P",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.3180,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "#01717D",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004189,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25599,
          "tankName": "NO.1 WATER BALLAST TANK",
          "tankShortName": "WB1S",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.3210,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004190,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25600,
          "tankName": "NO.2 WATER BALLAST TANK",
          "tankShortName": "WB2P",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.3120,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004191,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25601,
          "tankName": "NO.2 WATER BALLAST TANK",
          "tankShortName": "WB2S",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.3170,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004192,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25602,
          "tankName": "NO.3 WATER BALLAST TANK",
          "tankShortName": "WB3P",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.2910,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004193,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25603,
          "tankName": "NO.3 WATER BALLAST TANK",
          "tankShortName": "WB3S",
          "temperature": null,
          "quantity": 9000.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 28.2990,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004194,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25604,
          "tankName": "NO.4 WATER BALLAST TANK",
          "tankShortName": "WB4P",
          "temperature": null,
          "quantity": 8900.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 29.8670,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004195,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25605,
          "tankName": "NO.4 WATER BALLAST TANK",
          "tankShortName": "WB4S",
          "temperature": null,
          "quantity": 8900.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 29.8950,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004196,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25606,
          "tankName": "NO.5 WATER BALLAST TANK",
          "tankShortName": "WB5P",
          "temperature": null,
          "quantity": 7600.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 25.8700,
          "sg": 1.0250,
          "active": false
        },
        {
          "cargoId": 0,
          "colorCode": "",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100004197,
          "dischargePatternId": 4887,
          "rdgUllage": null,
          "tankId": 25607,
          "tankName": "NO.5 WATER BALLAST TANK",
          "tankShortName": "WB5S",
          "temperature": null,
          "quantity": 7600.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "sounding": 25.8400,
          "sg": 1.0250,
          "active": false
        }
      ],
      "portDischargePlanRobDetails": [
        {
          "id": 100002702,
          "dischargePatternId": 4887,
          "tankId": 25615,
          "tankName": "NO.2  FUEL OIL TANK",
          "tankShortName": "FO2S",
          "quantity": 5.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "density": 0.9800,
          "colorCode": "#c60a09",
          "active": false
        },
        {
          "id": 100002703,
          "dischargePatternId": 4887,
          "tankId": 25619,
          "tankName": "BOILER F.O.SERV.TANK",
          "tankShortName": "BFOSV",
          "quantity": 8.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "density": 0.9800,
          "colorCode": "#c60a09",
          "active": false
        },
        {
          "id": 100002704,
          "dischargePatternId": 4887,
          "tankId": 25625,
          "tankName": "NO.2 D.O.SERV.TANK",
          "tankShortName": "DOSV2",
          "quantity": 4.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "density": 0.8800,
          "colorCode": "#fa8424",
          "active": false
        },
        {
          "id": 100002705,
          "dischargePatternId": 4887,
          "tankId": 25636,
          "tankName": "DRINKING WATER TANK",
          "tankShortName": "DWP",
          "quantity": 7.0000,
          "actualPlanned": 2,
          "arrivalDeparture": 1,
          "density": 1.0000,
          "colorCode": "#5aa1a3",
          "active": false
        }
      ],
      "portDischargePlanStowageDetails": [
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005298,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25585,
          "tankName": "NO.1  WING CARGO OIL TANK",
          "tankShortName": "1P",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 17365.9000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3110,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005299,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25586,
          "tankName": "NO.1  WING CARGO OIL TANK",
          "tankShortName": "1S",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 17365.9000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3110,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005300,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25581,
          "tankName": "NO.2 CENTER CARGO OIL TANK",
          "tankShortName": "2C",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 23548.1000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.2440,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005301,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25589,
          "tankName": "NO.3 WING CARGO OIL TANK",
          "tankShortName": "3P",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 16942.7000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3780,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005302,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25590,
          "tankName": "NO.3 WING CARGO OIL TANK",
          "tankShortName": "3S",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 16942.7000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3780,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005303,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25583,
          "tankName": "NO.4 CENTER CARGO OIL TANK",
          "tankShortName": "4C",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 23548.1000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.2490,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005304,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25593,
          "tankName": "NO.5 WING CARGO OIL TANK",
          "tankShortName": "5P",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 14426.5000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.4490,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005305,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25594,
          "tankName": "NO.5 WING CARGO OIL TANK",
          "tankShortName": "5S",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 14426.5000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.4490,
          "active": false
        },
        {
          "abbreviation": "ARM",
          "api": 30.8000,
          "cargoNominationId": 17759,
          "cargoId": 0,
          "colorCode": "#f3eb12",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005306,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25595,
          "tankName": "SLOP TANK",
          "tankShortName": "SLP",
          "temperature": 105.4000,
          "weight": null,
          "quantity": 3437.9000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3480,
          "active": false
        },
        {
          "abbreviation": "ARL",
          "api": 33.4000,
          "cargoNominationId": 17760,
          "cargoId": 0,
          "colorCode": "#f21818",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005307,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25580,
          "tankName": "NO.1 CENTER CARGO OIL TANK",
          "tankShortName": "1C",
          "temperature": 118.8000,
          "weight": null,
          "quantity": 24666.1000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.2350,
          "active": false
        },
        {
          "abbreviation": "ARL",
          "api": 33.4000,
          "cargoNominationId": 17760,
          "cargoId": 0,
          "colorCode": "#f21818",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005308,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25582,
          "tankName": "NO.3 CENTER CARGO OIL TANK",
          "tankShortName": "3C",
          "temperature": 118.8000,
          "weight": null,
          "quantity": 23011.4000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.2080,
          "active": false
        },
        {
          "abbreviation": "ARL",
          "api": 33.4000,
          "cargoNominationId": 17760,
          "cargoId": 0,
          "colorCode": "#f21818",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005309,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25584,
          "tankName": "NO.5 CENTER CARGO OIL TANK",
          "tankShortName": "5C",
          "temperature": 118.8000,
          "weight": null,
          "quantity": 27518.4000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.1300,
          "active": false
        },
        {
          "abbreviation": "ARL",
          "api": 33.4000,
          "cargoNominationId": 17760,
          "cargoId": 0,
          "colorCode": "#f21818",
          "correctedUllage": null,
          "correctionFactor": null,
          "fillingPercentage": "",
          "id": 100005310,
          "dischargePatternId": 4887,
          "observedBarrels": null,
          "observedBarrelsAt60": null,
          "observedM3": null,
          "rdgUllage": null,
          "tankId": 25596,
          "tankName": "SLOP TANK",
          "tankShortName": "SLS",
          "temperature": 118.8000,
          "weight": null,
          "quantity": 3359.5000,
          "actualPlanned": 2,
          "arrivalDeparture": 2,
          "ullage": 1.3480,
          "active": false
        }
      ],
      "dischargePlanCommingleDetails": [],
      "bunkerRearTanks": [
        [
          {
            "id": 25636,
            "categoryId": 3,
            "categoryName": "Fresh Water Tank",
            "name": "DRINKING WATER TANK",
            "frameNumberFrom": "5",
            "frameNumberTo": "13",
            "shortName": "DWP",
            "fullCapacityCubm": "369.4000",
            "density": 1.0000,
            "group": 1,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25638,
            "categoryId": 3,
            "categoryName": "Fresh Water Tank",
            "name": "DIST.WATER TANK",
            "frameNumberFrom": "13",
            "frameNumberTo": "15",
            "shortName": "DSWP",
            "fullCapacityCubm": "117.0000",
            "density": 1.0000,
            "group": 1,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 26003,
            "categoryId": 23,
            "categoryName": "Fresh Tank Void",
            "name": "APT",
            "frameNumberFrom": "0",
            "frameNumberTo": "15",
            "shortName": "APT1",
            "fullCapacityCubm": null,
            "density": null,
            "group": 1,
            "order": 3,
            "slopTank": false
          },
          {
            "id": 25640,
            "categoryId": 3,
            "categoryName": "Fresh Water Tank",
            "name": "COOLING WATER TANK",
            "frameNumberFrom": "10",
            "frameNumberTo": "15",
            "shortName": "FWC",
            "fullCapacityCubm": "29.5000",
            "density": 1.0000,
            "group": 1,
            "order": 3,
            "slopTank": false
          },
          {
            "id": 25639,
            "categoryId": 3,
            "categoryName": "Fresh Water Tank",
            "name": "DIST.WATER TANK",
            "frameNumberFrom": "13",
            "frameNumberTo": "15",
            "shortName": "DSWS",
            "fullCapacityCubm": "117.0000",
            "density": 1.0000,
            "group": 1,
            "order": 4,
            "slopTank": false
          },
          {
            "id": 25637,
            "categoryId": 3,
            "categoryName": "Fresh Water Tank",
            "name": "FRESH WATER TANK",
            "frameNumberFrom": "5",
            "frameNumberTo": "13",
            "shortName": "FWS",
            "fullCapacityCubm": "369.4000",
            "density": 1.0000,
            "group": 1,
            "order": 5,
            "slopTank": false
          }
        ]
      ],
      "bunkerTanks": [
        [
          {
            "id": 25614,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "NO.2  FUEL OIL TANK",
            "frameNumberFrom": "15",
            "frameNumberTo": "39",
            "shortName": "FO2P",
            "fullCapacityCubm": "1852.0000",
            "density": 0.9800,
            "group": 2,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25612,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "NO.1  FUEL OIL TANK",
            "frameNumberFrom": "39",
            "frameNumberTo": "49",
            "shortName": "FO1P",
            "fullCapacityCubm": "2490.5000",
            "density": 0.9800,
            "group": 2,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 26004,
            "categoryId": 22,
            "categoryName": "Fuel Void",
            "name": "FUEL VOID 1",
            "frameNumberFrom": "15",
            "frameNumberTo": "49",
            "shortName": "VOID1",
            "fullCapacityCubm": null,
            "density": null,
            "group": 2,
            "order": 3,
            "slopTank": false
          },
          {
            "id": 26005,
            "categoryId": 22,
            "categoryName": "Fuel Void",
            "name": "FUEL VOID 2",
            "frameNumberFrom": "15",
            "frameNumberTo": "43",
            "shortName": "VOID2",
            "fullCapacityCubm": null,
            "density": null,
            "group": 2,
            "order": 4,
            "slopTank": false
          },
          {
            "id": 25616,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "H.F.O.SERV. TANK",
            "frameNumberFrom": "43",
            "frameNumberTo": "47",
            "shortName": "FOSV",
            "fullCapacityCubm": "66.8000",
            "density": 0.9800,
            "group": 2,
            "order": 5,
            "slopTank": false
          },
          {
            "id": 25625,
            "categoryId": 6,
            "categoryName": "Diesel Oil Tank",
            "name": "NO.2 D.O.SERV.TANK",
            "frameNumberFrom": "22",
            "frameNumberTo": "24",
            "shortName": "DOSV2",
            "fullCapacityCubm": "27.4000",
            "density": 0.8500,
            "group": 2,
            "order": 6,
            "slopTank": false
          },
          {
            "id": 25624,
            "categoryId": 6,
            "categoryName": "Diesel Oil Tank",
            "name": "NO.1 D.O. SERV.TANK",
            "frameNumberFrom": "24",
            "frameNumberTo": "26",
            "shortName": "DOSV1",
            "fullCapacityCubm": "32.4000",
            "density": 0.8500,
            "group": 2,
            "order": 7,
            "slopTank": false
          },
          {
            "id": 25617,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "H.F.O.SETT. TANK",
            "frameNumberFrom": "39",
            "frameNumberTo": "43",
            "shortName": "FOST",
            "fullCapacityCubm": "64.1000",
            "density": 0.9800,
            "group": 2,
            "order": 8,
            "slopTank": false
          },
          {
            "id": 25620,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "F.O.SLUDGE TANK",
            "frameNumberFrom": "38",
            "frameNumberTo": "42",
            "shortName": "FOS",
            "fullCapacityCubm": "5.5000",
            "density": 0.9800,
            "group": 2,
            "order": 9,
            "slopTank": false
          },
          {
            "id": 25623,
            "categoryId": 6,
            "categoryName": "Diesel Oil Tank",
            "name": "NO.2 DIESEL OIL TANK",
            "frameNumberFrom": "15",
            "frameNumberTo": "22",
            "shortName": "DO2S",
            "fullCapacityCubm": "278.1000",
            "density": 0.8500,
            "group": 2,
            "order": 9,
            "slopTank": false
          },
          {
            "id": 25622,
            "categoryId": 6,
            "categoryName": "Diesel Oil Tank",
            "name": "NO.1 DIESEL OIL TANK",
            "frameNumberFrom": "22",
            "frameNumberTo": "26",
            "shortName": "DO1S",
            "fullCapacityCubm": "175.2000",
            "density": 0.8500,
            "group": 2,
            "order": 10,
            "slopTank": false
          },
          {
            "id": 25619,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "BOILER F.O.SERV.TANK",
            "frameNumberFrom": "34",
            "frameNumberTo": "39",
            "shortName": "BFOSV",
            "fullCapacityCubm": "67.2000",
            "density": 0.9800,
            "group": 2,
            "order": 11,
            "slopTank": false
          },
          {
            "id": 25615,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "NO.2  FUEL OIL TANK",
            "frameNumberFrom": "26",
            "frameNumberTo": "39",
            "shortName": "FO2S",
            "fullCapacityCubm": "1259.2000",
            "density": 0.9800,
            "group": 2,
            "order": 12,
            "slopTank": false
          },
          {
            "id": 25613,
            "categoryId": 5,
            "categoryName": "Fuel Oil Tank",
            "name": "NO.1  FUEL OIL TANK",
            "frameNumberFrom": "39",
            "frameNumberTo": "49",
            "shortName": "FO1S",
            "fullCapacityCubm": "2154.3000",
            "density": 0.9800,
            "group": 2,
            "order": 13,
            "slopTank": false
          }
        ]
      ],
      "ballastFrontTanks": [
        [
          {
            "id": 25611,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "FORE PEAK TANK(PORT USE)",
            "frameNumberFrom": "103",
            "frameNumberTo": "FE",
            "shortName": "UFPT",
            "fullCapacityCubm": "5156.5000",
            "density": 1.0250,
            "group": 0,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25597,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "FORE PEAK TANK",
            "frameNumberFrom": "103",
            "frameNumberTo": "FE",
            "shortName": "LFPT",
            "fullCapacityCubm": "5444.2000",
            "density": 1.0250,
            "group": 0,
            "order": 2,
            "slopTank": false
          }
        ]
      ],
      "ballastCenterTanks": [
        [
          {
            "id": 25608,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "AFT WATER BALLAST TANK",
            "frameNumberFrom": "15",
            "frameNumberTo": "39",
            "shortName": "AWBP",
            "fullCapacityCubm": "1024.9000",
            "density": 1.0250,
            "group": 0,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 26006,
            "categoryId": 16,
            "categoryName": "Ballast Void",
            "name": "VOID",
            "frameNumberFrom": "39",
            "frameNumberTo": "49",
            "shortName": "VOID3",
            "fullCapacityCubm": null,
            "density": null,
            "group": 0,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25606,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.5 WATER BALLAST TANK",
            "frameNumberFrom": "49",
            "frameNumberTo": "61",
            "shortName": "WB5P",
            "fullCapacityCubm": "8561.9000",
            "density": 1.0250,
            "group": 0,
            "order": 3,
            "slopTank": false
          },
          {
            "id": 25604,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.4 WATER BALLAST TANK",
            "frameNumberFrom": "61",
            "frameNumberTo": "71",
            "shortName": "WB4P",
            "fullCapacityCubm": "8743.7000",
            "density": 1.0250,
            "group": 0,
            "order": 4,
            "slopTank": false
          },
          {
            "id": 25602,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.3 WATER BALLAST TANK",
            "frameNumberFrom": "71",
            "frameNumberTo": "81",
            "shortName": "WB3P",
            "fullCapacityCubm": "8875.8000",
            "density": 1.0250,
            "group": 0,
            "order": 5,
            "slopTank": false
          },
          {
            "id": 25600,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.2 WATER BALLAST TANK",
            "frameNumberFrom": "81",
            "frameNumberTo": "91",
            "shortName": "WB2P",
            "fullCapacityCubm": "8873.6000",
            "density": 1.0250,
            "group": 0,
            "order": 6,
            "slopTank": false
          },
          {
            "id": 25598,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.1 WATER BALLAST TANK",
            "frameNumberFrom": "91",
            "frameNumberTo": "103",
            "shortName": "WB1P",
            "fullCapacityCubm": "8906.5000",
            "density": 1.0250,
            "group": 0,
            "order": 7,
            "slopTank": false
          },
          {
            "id": 25609,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "AFT WATER BALLAST TANK",
            "frameNumberFrom": "15",
            "frameNumberTo": "39",
            "shortName": "AWBS",
            "fullCapacityCubm": "1024.9000",
            "density": 1.0250,
            "group": 0,
            "order": 8,
            "slopTank": false
          },
          {
            "id": 26007,
            "categoryId": 16,
            "categoryName": "Ballast Void",
            "name": "VOID",
            "frameNumberFrom": "39",
            "frameNumberTo": "49",
            "shortName": "VOID4",
            "fullCapacityCubm": null,
            "density": null,
            "group": 0,
            "order": 9,
            "slopTank": false
          },
          {
            "id": 25607,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.5 WATER BALLAST TANK",
            "frameNumberFrom": "49",
            "frameNumberTo": "61",
            "shortName": "WB5S",
            "fullCapacityCubm": "8560.4000",
            "density": 1.0250,
            "group": 0,
            "order": 10,
            "slopTank": false
          },
          {
            "id": 25605,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.4 WATER BALLAST TANK",
            "frameNumberFrom": "61",
            "frameNumberTo": "71",
            "shortName": "WB4S",
            "fullCapacityCubm": "8741.7000",
            "density": 1.0250,
            "group": 0,
            "order": 11,
            "slopTank": false
          },
          {
            "id": 25603,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.3 WATER BALLAST TANK",
            "frameNumberFrom": "71",
            "frameNumberTo": "81",
            "shortName": "WB3S",
            "fullCapacityCubm": "8873.8000",
            "density": 1.0250,
            "group": 0,
            "order": 12,
            "slopTank": false
          },
          {
            "id": 25601,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.2 WATER BALLAST TANK",
            "frameNumberFrom": "81",
            "frameNumberTo": "91",
            "shortName": "WB2S",
            "fullCapacityCubm": "8871.5000",
            "density": 1.0250,
            "group": 0,
            "order": 13,
            "slopTank": false
          },
          {
            "id": 25599,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "NO.1 WATER BALLAST TANK",
            "frameNumberFrom": "91",
            "frameNumberTo": "103",
            "shortName": "WB1S",
            "fullCapacityCubm": "8904.4000",
            "density": 1.0250,
            "group": 0,
            "order": 14,
            "slopTank": false
          }
        ]
      ],
      "ballastRearTanks": [
        [
          {
            "id": 25610,
            "categoryId": 2,
            "categoryName": "Water Ballast Tank",
            "name": "AFT PEAK TANK",
            "frameNumberFrom": "AE",
            "frameNumberTo": "15",
            "shortName": "APT",
            "fullCapacityCubm": "2574.4000",
            "density": 1.0250,
            "group": 0,
            "order": 1,
            "slopTank": false
          }
        ]
      ],
      "cargoTanks": [
        [
          {
            "id": 25595,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "SLOP TANK",
            "frameNumberFrom": "49",
            "frameNumberTo": "52",
            "shortName": "SLP",
            "fullCapacityCubm": "4117.3000",
            "density": 1.3000,
            "group": 1,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25593,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.5 WING CARGO OIL TANK",
            "frameNumberFrom": "52",
            "frameNumberTo": "61",
            "shortName": "5P",
            "fullCapacityCubm": "17277.4000",
            "density": 1.3000,
            "group": 1,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25584,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.5 CENTER CARGO OIL TANK",
            "frameNumberFrom": "49",
            "frameNumberTo": "61",
            "shortName": "5C",
            "fullCapacityCubm": "33725.1000",
            "density": 1.3000,
            "group": 1,
            "order": 3,
            "slopTank": false
          },
          {
            "id": 25596,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "SLOP TANK",
            "frameNumberFrom": "49",
            "frameNumberTo": "52",
            "shortName": "SLS",
            "fullCapacityCubm": "4117.3000",
            "density": 1.3000,
            "group": 1,
            "order": 4,
            "slopTank": false
          },
          {
            "id": 25594,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.5 WING CARGO OIL TANK",
            "frameNumberFrom": "52",
            "frameNumberTo": "61",
            "shortName": "5S",
            "fullCapacityCubm": "17277.4000",
            "density": 1.3000,
            "group": 1,
            "order": 5,
            "slopTank": false
          }
        ],
        [
          {
            "id": 25591,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.4 WING CARGO OIL TANK",
            "frameNumberFrom": "61",
            "frameNumberTo": "71",
            "shortName": "4P",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 2,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25583,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.4 CENTER CARGO OIL TANK",
            "frameNumberFrom": "61",
            "frameNumberTo": "71",
            "shortName": "4C",
            "fullCapacityCubm": "28201.6000",
            "density": 1.3000,
            "group": 2,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25592,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.4 WING CARGO OIL TANK",
            "frameNumberFrom": "61",
            "frameNumberTo": "71",
            "shortName": "4S",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 2,
            "order": 3,
            "slopTank": false
          }
        ],
        [
          {
            "id": 25589,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.3 WING CARGO OIL TANK",
            "frameNumberFrom": "71",
            "frameNumberTo": "81",
            "shortName": "3P",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 3,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25582,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.3 CENTER CARGO OIL TANK",
            "frameNumberFrom": "71",
            "frameNumberTo": "81",
            "shortName": "3C",
            "fullCapacityCubm": "28201.6000",
            "density": 1.3000,
            "group": 3,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25590,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.3 WING CARGO OIL TANK",
            "frameNumberFrom": "71",
            "frameNumberTo": "81",
            "shortName": "3S",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 3,
            "order": 3,
            "slopTank": false
          }
        ],
        [
          {
            "id": 25587,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.2 WING CARGO OIL TANK",
            "frameNumberFrom": "81",
            "frameNumberTo": "91",
            "shortName": "2P",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 4,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25581,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.2 CENTER CARGO OIL TANK",
            "frameNumberFrom": "81",
            "frameNumberTo": "91",
            "shortName": "2C",
            "fullCapacityCubm": "28201.6000",
            "density": 1.3000,
            "group": 4,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25588,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.2 WING CARGO OIL TANK",
            "frameNumberFrom": "81",
            "frameNumberTo": "91",
            "shortName": "2S",
            "fullCapacityCubm": "20290.8000",
            "density": 1.3000,
            "group": 4,
            "order": 3,
            "slopTank": false
          }
        ],
        [
          {
            "id": 25585,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.1  WING CARGO OIL TANK",
            "frameNumberFrom": "91",
            "frameNumberTo": "103",
            "shortName": "1P",
            "fullCapacityCubm": "20797.7000",
            "density": 1.3000,
            "group": 5,
            "order": 1,
            "slopTank": false
          },
          {
            "id": 25580,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.1 CENTER CARGO OIL TANK",
            "frameNumberFrom": "91",
            "frameNumberTo": "103",
            "shortName": "1C",
            "fullCapacityCubm": "30229.5000",
            "density": 1.3000,
            "group": 5,
            "order": 2,
            "slopTank": false
          },
          {
            "id": 25586,
            "categoryId": 1,
            "categoryName": "Cargo Tank",
            "name": "NO.1  WING CARGO OIL TANK",
            "frameNumberFrom": "91",
            "frameNumberTo": "103",
            "shortName": "1S",
            "fullCapacityCubm": "20797.7000",
            "density": 1.3000,
            "group": 5,
            "order": 3,
            "slopTank": false
          }
        ]
      ]
    };
    return of(response)
  }

  /**
   * method for save ullage update for discharge plan
   *
   * @memberof UllageUpdateApiService
   */
  dischargePlanUpdateUllage(data: IUllageSaveDetails) {
    return this.commonApiService.post<IUllageSaveDetails, IResponse>(`discharge/ullage-update`, data);
  }
}
